package:
  name: PyJWT
  version: 2.10.1
  top-level:
    - jwt

source:
  url: https://files.pythonhosted.org/packages/py3/p/pyjwt/PyJWT-2.10.1-py3-none-any.whl
  sha256: dcdd193e30abefd5debf142f9adfcdd2b58004e644f25406ffaebd50bd98dacb

requirements:
  run:
    - cryptography
    - ssl

about:
  home: https://github.com/jpadilla/pyjwt
  PyPI: https://pypi.org/project/PyJWT
  summary: JSON Web Token implementation in Python
  license: MIT

extra:
  recipe-maintainers:
    - rpwagner
