package:
  name: geopy
  version: 2.4.1
  top-level:
    - geopy
source:
  url: https://files.pythonhosted.org/packages/py3/g/geopy/geopy-2.4.1-py3-none-any.whl
  sha256: ae8b4bc5c1131820f4d75fce9d4aaaca0c85189b3aa5d64c3dcaf5e3b7b882a7
about:
  home: https://github.com/geopy/geopy
  PyPI: https://pypi.org/project/geopy
  summary: Python Geocoding Toolbox
  license: MIT
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
